db:
  image: mysql:8.0.33
  command: --default-authentication-plugin=mysql_native_password
  restart: always

user:
  image: mysql:8.0.33
  command: --default-authentication-plugin=mysql_native_password
  restart: always