## 环境模块
mode:
  name: 'production'
  development: false

db:
  type: mysql
  autoLoadEntities: true
  migrationsRun: true
  host: 39.96.165.134
  port: 13306
  username: root
  password: 8Kytb8EzbAFrbtyC
  database: nest
  timezone: +08:00
  synchronize: false
  logging: true
  logger: file

redis:
  host: 39.96.165.134
  port: 6379
  password: 123456
  # 默认缓存时间, 单位秒
  expiration: 3600

user:
  image: mysql:8.0.32
  command: --default-authentication-plugin=mysql_native_password
  restart: always
