db:
  image: mysql:8.0.31
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  host: 127.0.0.1
  password: dev_secret
  SYNCHRONIZE: true,
  LOGGING: true

user:
  image: mysql:8.0.31
  command: --default-authentication-plugin=mysql_native_password
  restart: always

logger:
  maxSize: 20m # 日志文件的最大大小
  maxFiles: 14d # 日志文件的最大保留时间

jwt:
  secret: dev_secret
  algorithm: HS256
  expiration: 1h # JWT的过期时间
  refreshTokenExpiration: 30d # 刷新令牌的过期时间
  enable: true # 是否启用JWT认证

defaultRole:
  id: 1
  name: 普通用户

