mode:
  name: test
  development: false

db:
  type: postgres
  host: 127.0.0.1
  port: 5432
  username: postgres
  password: postgres
  database: survey_statistics_test
  synchronize: true
  logging: false
  createForeignKeyConstraints: false

redis:
  host: 127.0.0.1
  port: 6379
  password: null
  expiration: 3600

jwt:
  secret: test_secret

cors:
  origins:
    - http://localhost:3000

security:
  bodyLimit: 100kb
