mode:
    name: development
    development: true

db:
    type: postgres
    host: 127.0.0.1
    port: 5432
    username: postgres
    password: postgres
    database: survey_statistics
    synchronize: true
    logging: true
    logger: file
    createForeignKeyConstraints: false

redis:
    host: 127.0.0.1
    port: 6379
    password: null
    expiration: 3600

jwt:
    secret: dev_secret

cors:
    origins:
        - http://localhost:3000
        - http://localhost:5173
        - http://localhost:3003

security:
    bodyLimit: 100kb
