db:
    type: postgres
    host: 127.0.0.1
    port: 5432
    username: postgres
    password: postgres
    database: survey_statistics
    synchronize: true
    logging: true
    logger: file
    createForeignKeyConstraints: false

redis:
    host: 127.0.0.1
    port: 6379
    password: null # 覆盖 config.yml；本地 docker redis 无密码
    expiration: 3600

jwt:
    secret: dev_secret
