db:
    type: postgres
    host: 127.0.0.1
    port: 5432
    username: postgres
    password: postgres
    database: survey_statistics
    synchronize: false
    logging: false
    logger: file
    createForeignKeyConstraints: false

redis:
    host: 127.0.0.1
    port: 6379
    password: null
    expiration: 3600

jwt:
    secret: prod_secret

cors:
    origins:
        - https://your-production-domain.com

security:
    bodyLimit: 100kb
